application:
  title: Parking Control
  description: Rest API for parking control
  version: 0.1

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  devtools:
    livereload:
      port: 35730
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test_job
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
